### ISSUE TITLE
Consider rephrasing "Logical Access"

### ISSUE THREAD

**Issue by scriptingxss** [OWASP/owasp-istg#1]
The term "logical" has a certain connotation thats similar to rational and analytical but in the context of the guide, it feels misaligned creating inertia. 

 Consider simplifying "Logical Access" to something like “Authorization Access” "Credential Access" or “Permission Access”.

**Comment by rockhoppersec** [comment]
Good suggestion, and I agree! "Logical Access" is a remnant from the first version of this guide and might be too ambiguous.

In my opinion, "Authorization Access" is the best option. "Permission Access" would result in the same abbreviation as "Physical Access".

**Comment by scriptingxss** [comment]
Mindmap image of test cases also needs updating https://github.com/OWASP/owasp-istg/blob/main/src/img/Mindmap.png

**Comment by rockhoppersec** [comment]
@scriptingxss: Updated the mindmap in https://github.com/OWASP/owasp-istg/commit/cfe958a2a0f64ae4894128357f6f6ae3cea739ea. However, the component overview (formerly mindmap) is not affected by the logical > authorization access change. I believe this belongs to https://github.com/OWASP/owasp-istg/issues/4.
