### ISSUE TITLE
Overview of Data Exchange Services (ISTG-DES) identical to Memory (ISTG-MEM)

### ISSUE THREAD

**Issue by MartinNoc** [OWASP/owasp-istg#12]
The Overview section of Data Exchange Service is identical to Memory.
Seems like there happend a copy-paste mistake.

DES:
https://github.com/OWASP/owasp-istg/blob/main/src/03_test_cases/data_exchange_services/README.md#overview

MEM:
https://github.com/OWASP/owasp-istg/blob/main/src/03_test_cases/memory/README.md#overview

**Comment by MartinNoc** [comment]
@scriptingxss 
@rockhoppersec 
Thanks in advance :)

**Comment by rockhoppersec** [comment]
Hi Martin, Good catch! I'll fix it as soon as I have a chance. Thanks for bringing it to our attention.
