### ISSUE TITLE
Input validation category abbreviation - ISTG><MASTG>WSTG

### ISSUE THREAD

**Issue by scriptingxss** [OWASP/owasp-istg#4]
@rockhoppersec Should ISTG align input validation taxonomies from flag ship testing guide projects?

- ISTG abbreviates the input validation category with INVAL e.g. [IOT-DES-INVAL](https://github.com/OWASP/owasp-istg/blob/main/src/03_test_cases/data_exchange_services/README.md#input-validation-iot-des-inval). 
- WSTG abbreviates using INPV e.g. [WSTG-INPV-01](https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/07-Input_Validation_Testing/01-Testing_for_Reflected_Cross_Site_Scripting)
- MASTG inherits MASVS abbreviations with [MASVS-CODE-4](https://mas.owasp.org/MASVS/controls/MASVS-CODE-4/) for [input validation](https://mas.owasp.org/MASTG/tests/android/MASVS-CODE/MASTG-TEST-0002/) and [testing for injection](https://mas.owasp.org/MASTG/tests/android/MASVS-CODE/MASTG-TEST-0025/)

**Comment by rockhoppersec** [comment]
Yes, that's a good idea. In my opinion, INPV is more intuitive than CODE.

**Comment by rockhoppersec** [comment]
Updated component overview (formerly mindmap) in https://github.com/OWASP/owasp-istg/commit/cfe958a2a0f64ae4894128357f6f6ae3cea739ea
